"""Delete meeting result table

Revision ID: 039425897c3b
Revises: 82ecac55f540
Create Date: 2026-07-06 17:32:01.125525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '039425897c3b'
down_revision: Union[str, Sequence[str], None] = '82ecac55f540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_audio_files', sa.Column('transcription', sa.Text(), nullable=True))
    op.add_column('meeting_audio_files', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('meeting_audio_files', sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('meeting_audio_files', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_audio_files', 'status')
    op.drop_column('meeting_audio_files', 'action_items')
    op.drop_column('meeting_audio_files', 'summary')
    op.drop_column('meeting_audio_files', 'transcription')
    # ### end Alembic commands ###
