"""Add column type to meeting table

Revision ID: 3d8d047f869a
Revises: f9cc91de8fe9
Create Date: 2026-07-21 18:33:23.467700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8d047f869a'
down_revision: Union[str, Sequence[str], None] = 'f9cc91de8fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'type')
    # ### end Alembic commands ###
