"""add speakers field in meeting table

Revision ID: 7744172db2fc
Revises: 3d8d047f869a
Create Date: 2026-07-24 16:19:38.180609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7744172db2fc'
down_revision: Union[str, Sequence[str], None] = '3d8d047f869a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('speakers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'speakers')
    # ### end Alembic commands ###
