"""Add retry_count column on meeting audio file table

Revision ID: c2867f4a45c6
Revises: f19261b0e6d7
Create Date: 2026-08-12 17:15:50.237435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2867f4a45c6'
down_revision: Union[str, Sequence[str], None] = 'f19261b0e6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_audio_files', sa.Column('retry_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_audio_files', 'retry_count')
    # ### end Alembic commands ###
