"""update-audio_url-field-to-description

Revision ID: d724e834edd7
Revises: 0e4071b7c07f
Create Date: 2026-07-05 18:02:36.604069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd724e834edd7'
down_revision: Union[str, Sequence[str], None] = '0e4071b7c07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('meetings', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('meetings', 'description')
    # ### end Alembic commands ###
